--CREATE TABLE SALES
--(Date VARCHAR(50),
--Order_id INT,
--Item_id INT,
--Customer_id INT,
--Quantity INT,
--Revenue INT
--)

--CREATE TABLE ITEMS
--(Item_id INT,
--Item_name VARCHAR(50),
--Price INT,
--department VARCHAR(50)
--)

--CREATE TABLE CUSTOMERS
--(Customer_id INT,
--First_name VARCHAR(50),
--Last_name VARCHAR(50),
--Address VARCHAR(50)
--)

--Q1 1. Pull total number of orders that were completed on 18th March 2023
--SELECT COUNT(DISTINCT(Order_id))
--FROM SALES
--WHERE Date = '03-18-2023'

--Q2 Pull total number of orders that were completed on 18th March 2023 with the first name ‘John’ and last name ‘Doe’
--SELECT COUNT(DISTINCT(Order_id))
--FROM SALES
--FULL OUTER JOIN CUSTOMERS
--ON CUSTOMERS.Customer_id=SALES.Customer_id
--WHERE Date = '03-18-2023' AND First_name='JOHN' AND Last_name='DOE'

--Q3 Pull total number of customers that purchased in January 2023 and the average amount spend per customer
--SELECT SALES.Customer_id,First_name,Last_name, AVG(Revenue)
--FROM CUSTOMERS
--FULL OUTER JOIN SALES
--ON SALES.Customer_id=CUSTOMERS.Customer_id
--WHERE Date LIKE '%-1-2023'
--GROUP BY SALES.Customer_id 

--Q4 Pull the departments that generated less than $600 in 2022
--SELECT department, SUM(Revenue)
--FROM ITEMS
--FULL OUTER JOIN SALES
--ON ITEMS.Item_id=SALES.Item_id
--WHERE SUM(Revenue) < 600 AND Date LIKE '%-%-2022'
--GROUP BY department

--Q5 What is the most and least revenue we have generated by an order
--SELECT TOP 1 Order_id ,SUM(Revenue) as 'Maximum Revenue'
--FROM SALES
--GROUP BY Order_id
--ORDER BY [Maximum Revenue] DESC

--SELECT TOP 1 Order_id ,SUM(Revenue) as 'Minimum Revenue'
--FROM SALES
--GROUP BY Order_id
--ORDER BY [Minimum Revenue] ASC

--Q6 What were the orders that were purchased in our most lucrative order
--SELECT TOP 1 Order_id ,SUM(Revenue) as 'Maximum Revenue', (SELECT Item_name AS ITEM_LIST FROM ITEMS)
--FROM SALES
--FULL OUTER JOIN ITEMS
--ON ITEMS.Item_id = SALES.Item_id 
--GROUP BY Order_id
--ORDER BY [Maximum Revenue] DESC


